---
services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${OIDC_POSTGRES_PASSWORD:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - internal

  authentik:
    image: ${OIDC_IMAGE:-ghcr.io/goauthentik/server}:${OIDC_TAG:-2025.12.1}
    restart: unless-stopped
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${OIDC_POSTGRES_PASSWORD}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${OIDC_SECRET_KEY:?secret key required}
    volumes:
      - ./data:/data
      - ./custom-templates:/templates
    ports:
      - ${COMPOSE_PORT_HTTP:-9000}:9000
      - ${COMPOSE_PORT_HTTPS:-9443}:9443
    networks:
      - internal

  authentik-worker:
    image: ${OIDC_IMAGE:-ghcr.io/goauthentik/server}:${OIDC_TAG:-2025.12.1}
    restart: unless-stopped
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${OIDC_POSTGRES_PASSWORD}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${OIDC_SECRET_KEY:?secret key required}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./certs:/certs
      - ./custom-templates:/templates
    networks:
      - internal

  inventarium-api:
    container_name: inventarium-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: ${APP_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      PLATFORM_ADMIN_USERNAME: ${PLATFORM_ADMIN_USERNAME}
      PLATFORM_ADMIN_PASSWORD_HASH: ${PLATFORM_ADMIN_PASSWORD_HASH}

      POSTGRES_HOST: postgresql
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      OIDC_POSTGRES_PASSWORD: ${OIDC_POSTGRES_PASSWORD}
      OIDC_SECRET_KEY: ${OIDC_SECRET_KEY}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_ISSUER_URI: ${OIDC_ISSUER_URI}
      OIDC_USER_INFO: ${OIDC_USER_INFO}
      OIDC_AUTH_URL: ${OIDC_AUTH_URL}
      OIDC_TOKEN_URL: ${OIDC_TOKEN_URL}
      OIDC_SCOPES: ${OIDC_SCOPES}
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:

volumes:
  database:
    driver: local