spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.yaml
    parameters:
      PLATFORM_ADMIN_USERNAME: ${PLATFORM_ADMIN_USERNAME}
      PLATFORM_ADMIN_PASSWORD_HASH: ${PLATFORM_ADMIN_PASSWORD_HASH}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}

  web:
    error:
      include-message: always

security:
  encryption:
    master-key: ${APP_MASTER_KEY}

oidc:
  client-id: ${OIDC_CLIENT_ID}
  client-secret: ${OIDC_CLIENT_SECRET}
  user-info-endpoint: ${OIDC_USER_INFO}
  auth-url: ${OIDC_AUTH_URL}
  token-url: ${OIDC_TOKEN_URL}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    oauth:
      client-id: ${OIDC_CLIENT_ID}
      client-secret: ${OIDC_CLIENT_SECRET}
      scopes: ${OIDC_SCOPES}

logging:
  level:
    root: ${LOG_LEVEL}